# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  snyk: snyk/snyk@1.7.0
jobs:
  build:
    docker:
      - image: cimg/node:latest
    steps:
      - checkout
      - run: npm install
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          severity-threshold: critical
          token-variable: SNYK_TOKEN
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
