# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
    snyk: snyk/snyk@1.7.0
jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - snyk/scan:
                fail-on-issues: false
                monitor-on-build: true
                severity-threshold: high
                token-variable: SNYK_TOKEN
workflows: null
