# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  snyk: snyk/snyk@1.7.0
jobs:
  build:
    docker:
      - image: cimg/node:16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          severity-threshold: critical
          token-variable: SNYK_TOKEN
workflows: null
